### PR TITLE
Add linux aarch64 wheel build support

### PR DESCRIPTION
**Pull request by odidev**
Add linux aarch64 wheel build support. 

Related to https://github.com/cher-nov/cryptg/issues/11 @cher-nov Could you please review this PR?

### CODE REVIEW

**Comment by cher-nov** [comment]
Thank you for the contribution and sorry for the delay!

Unfortunately, the repository is now in a non-release condition, as it has been stalled in the midst of the Rust-based version development. I plan to finish it until next year, and then I'll review your PR properly.

**Comment by Lonami** [comment]
I think CI is working now that  #13 was fixed (at least it worked on my test repo). We may try supporting aarch64 again after we polish it up and make sure it all works.

**Comment by odidev** [comment]
@cher-nov, did you get a chance to look into this PR? Thanks.

**Comment by Rongronggg9** [comment]
Is there any news on this?
Now that `cryptg` v0.3 was released and is the initial RIIR-ed release, it is a suitable time to distribute aarch64 wheels along with wheels other architectures.

RIIR is a piece of good news, meanwhile a piece of bad news. It effectively makes building it on QEMU-simulated aarch64 insanely painful. Typically speaking, despite the setup time of `rustup` (> 70s), `cryptg` needs > 700s to build. Previously the time is just 20s.

_Why QEMU? GHA only provides amd64 hosted runners._

**Comment by Lonami** [comment]
I've tried to resolve the conflicts, but since we're now using `cibuildwheel`, I may do something wrong in the "updating" process. I see `cibuildwheel` has a section for [Building non-native architectures using emulation](https://cibuildwheel.readthedocs.io/en/stable/faq/#emulation) which includes `aarch64` but I'm not sure if there's a particular reason why the old code uses `if: ${{ matrix.arch == 'aarch64' }}`, whereas their example uses `if: runner.os == 'Linux'` and `with: platforms: all`, so I would rather wait on @odidev since they're OP.

However I'm open to another PR with the necessary changes from someone more knowledgeable than me if OP doesn't respond.

**Comment by Rongronggg9** [comment]
`if: ${{ matrix.arch == 'aarch64' }}` is indeed a bit weird since there seems to be no disadvantage if we delete this line.

**Comment by Lonami** [comment]
Maybe it means it only uses qemu for that so the others are faster to build?

**Comment by Rongronggg9** [comment]
> Maybe it means it only uses qemu for that so the others are faster to build?

Nope. Setting up QEMU would not make builds for amd64/x86 using QEMU.

**Pull request merged**
